import type { Metadata } from "next";
import "./globals.css";
import { test } from "@/app/actions/test";
import { Toaster } from "@/components/ui/sonner";
import { ColorPickerProvider } from "@/components/color-picker/context";
import { ThemeProvider } from "@/components/theme-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await test();
  console.log(res, "?>?>?>1234");
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ColorPickerProvider initialColor="#0066FFFF">
            {children}
            <Toaster />
          </ColorPickerProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
