import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
import { ColorProvider } from "@/provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <ColorProvider initialColor="#0066FF">
            <div className="flex justify-center h-screen w-screen">
              {children}
            </div>
            <Toaster />
          </ColorProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
